#!/bin/bash
#
# Schedule Cron - Setup daily discovery
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CRON_FILE="/etc/cron.d/cmdb-discovery"

# Default schedule: 2am daily
SCHEDULE="${SCHEDULE:-0 2 * * *}"
SCRIPT_PATH="${SCRIPT_PATH:-$PROJECT_DIR/scripts/run-discovery.sh}"

# Create cron entry
create_cron() {
    cat > "$CRON_FILE" << EOF
# CMDB ServiceNow Discovery - Daily Schedule
# Generated by ti-team

SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
LOGFILE=/var/log/cmdb-discovery.log

$SCHEDULE root $SCRIPT_PATH >> \$LOGFILE 2>&1

EOF
    
    chmod 644 "$CRON_FILE"
    echo "Cron entry created at $CRON_FILE"
    echo ""
    echo "Schedule: $SCHEDULE"
}

# Remove cron entry
remove_cron() {
    if [ -f "$CRON_FILE" ]; then
        rm "$CRON_FILE"
        echo "Cron entry removed"
    else
        echo "No cron entry found"
    fi
}

# Show current cron
show_cron() {
    if [ -f "$CRON_FILE" ]; then
        echo "Current cron entry:"
        cat "$CRON_FILE"
    else
        echo "No cron entry configured"
    fi
}

case "${1:-}" in
    --install|-i)
        create_cron
        ;;
    --remove|-r)
        remove_cron
        ;;
    --show|-s)
        show_cron
        ;;
    *)
        echo "Usage: $0 {--install|--remove|--show}"
        echo ""
        echo "Options:"
        echo "  --install   Install daily cron job"
        echo "  --remove    Remove cron job"
        echo "  --show      Show current cron configuration"
        exit 1
        ;;
esac